const assert = require("assert");
const L = require("../site/assets/leaguelens.js");
const owner = require("./fixtures/owner_league_settings.json");
const gab = owner.gabagool.scoring_settings;
assert.strictEqual(L.plain(0.04), "0.04");
assert.strictEqual(L.plain(0.0400001), "0.0400001");
assert.strictEqual(L.plain(6), "6");
assert.strictEqual(L.plain(-0), "0");
assert.strictEqual(L.plain(1e-7), "0.0000001");
assert.strictEqual(L.plain(-2.5), "-2.5");
assert.strictEqual(L.plain(1e21), "1000000000000000000000");
assert.strictEqual(L.plain(5e-324).length, 326);
assert.throws(() => L.plain(NaN)); assert.throws(() => L.plain(Infinity)); assert.throws(() => L.plain("1"));
const w = L.effectiveWeights({ rec: -1, bonus_rec_te: 2, pass_yd: 0.04 });
assert.deepStrictEqual(w.TE, { receptions: 1, passing_yards: 0.04 });
assert.deepStrictEqual(w.WR, { receptions: -1, passing_yards: 0.04 });
assert.deepStrictEqual(w.QB, { receptions: -1, passing_yards: 0.04 });
const z = L.effectiveWeights({ rec: 1, bonus_rec_wr: -1 });
assert.ok(!("receptions" in z.WR) && z.RB.receptions === 1, "cancelled weight omitted");
assert.notStrictEqual(L.evidenceIdentity(L.effectiveWeights({ pass_yd: 0.04 })), L.evidenceIdentity(L.effectiveWeights({ pass_yd: 0.0400001 })));
assert.doesNotThrow(() => L.evidenceIdentity(L.effectiveWeights({ pass_yd: 1e-12, rec: 2e7 })), "identity total over accepted weights");
const c = L.classify(gab);
assert.deepStrictEqual(c.recurring, []);
assert.deepStrictEqual(c.rare.slice().sort(), ["fum_rec_td", "pass_2pt", "pass_td_50p", "rec_2pt", "rec_td_50p", "rush_2pt", "rush_td_50p", "st_td"]);
assert.ok(c.approx.includes("pass_int_td") && c.refused === false);
assert.ok(L.classify({ pass_yd: 0.04, rec_2pt: 3 }).recurring.includes("rec_2pt"), "rare above bound banners");
assert.deepStrictEqual(L.classify({ rec: 1, bonus_fd_wr: 0.5, fum: -1, zzz_new: 1 }).recurring.slice().sort(), ["bonus_fd_wr", "fum", "zzz_new"]);
assert.ok(L.classify({ fgm_yds: 0.1, def_td: 6 }).refused);
assert.ok(L.classify({ bonus_rush_td_qb: 2, pass_yd: 0.04 }).recurring.includes("bonus_rush_td_qb"));
assert.throws(() => L.classify({ pass_yd: "x" })); assert.throws(() => L.classify({ pass_yd: NaN }));
console.log("leaguelens_fixture: ok");
